### ISSUE TITLE
Seeing "Welcome to nginx!" on 3Bot deployment

### ISSUE THREAD

**Issue by scottyeager** [threefoldfoundation/info_tfgrid22_testgroup#5]
When I deployed my 3Bot from the marketplace, I could only access it via the external web gateway. Using either the regular or tls local connections shows this in the browser:

![image](https://user-images.githubusercontent.com/17682591/89370273-2fe17f80-d695-11ea-9dfe-84c70e428407.png)

Coming back after a few days, I now see this on the external domain too and cannot access my 3Bot. I have to reproduce with a new 3Bot deployment due to the max expiration on marketplace deployments currently being less than 24 hours in the future.

**Comment by xmonader** [comment]
Hi @scottyeager :wave: in the solution provisioned we only show the link with /admin to access the 3bot system.

Will come back with more info for the max expiration thing :)

**Comment by scottyeager** [comment]
Hey @xmonader! That makes sense, thanks. This is different than the behavior of the 3Bot server launched locally via 3sdk, which may explain my confusion. In both cases, it's not easy to get back to the solution once you've closed the browser tab that launches initially. I thought that launching 3Bot locally output its IP to the terminal, but I'm not seeing it this time. Anyway, that's another topic.

There is a big opportunity here, I think, to make things nice for users by giving them a link to get back to already deployed solutions in the marketplace. Reading the deployment (json?) file for the IP and remembering to append "/admin" is tricky, even for the technically inclined.

I'll look forward to news on extending expirations, so I can keep playing and trying to break stuff :)

**Comment by zaibon** [comment]
@xmonader but shouldn't we at least show a proper home page instead of the default nginx one ?
